// Runs every repository check in order and stops at the first failure.
//
// Usage: npm run check
//
// Order: format, lint, compile, types, test, scenarios, hygiene. Compile runs
// before the type check because the contract types it needs are generated by
// the build.
//
// Each step runs with Hardhat telemetry disabled and with its output piped
// through this script (so it is not attached to a terminal). Together these
// keep Hardhat from sending usage data or fetching its update banner. Apart
// from the one-time Solidity compiler download on the very first build, no
// step needs network access.

import { spawn } from "node:child_process";
import path from "node:path";

type Step = {
  readonly name: string;
  readonly command: string;
  readonly args: readonly string[];
  /** How the command is shown in the log. */
  readonly display: string;
};

const ROOT = path.join(import.meta.dirname, "..");
const BIN = path.join(ROOT, "node_modules", ".bin");

function tool(name: string, args: readonly string[]): Omit<Step, "name"> {
  return {
    command: path.join(BIN, name),
    args,
    display: [name, ...args].join(" "),
  };
}

const STEPS: readonly Step[] = [
  { name: "format", ...tool("prettier", ["--check", "."]) },
  {
    name: "lint",
    ...tool("solhint", [
      "--disc",
      "--noPoster",
      "--max-warnings",
      "0",
      "contracts/**/*.sol",
    ]),
  },
  { name: "compile", ...tool("hardhat", ["build"]) },
  { name: "types", ...tool("tsc", ["-p", "tsconfig.json"]) },
  { name: "test", ...tool("hardhat", ["test", "nodejs"]) },
  {
    name: "scenarios",
    command: process.execPath,
    args: ["scripts/scenarios.ts"],
    display: "node scripts/scenarios.ts",
  },
  {
    name: "hygiene",
    command: process.execPath,
    args: ["scripts/hygiene.ts"],
    display: "node scripts/hygiene.ts",
  },
];

function runStep(step: Step): Promise<number> {
  return new Promise((resolve) => {
    const child = spawn(step.command, step.args, {
      cwd: ROOT,
      env: { ...process.env, HARDHAT_DISABLE_TELEMETRY: "true" },
      stdio: ["ignore", "pipe", "pipe"],
    });
    child.stdout.on("data", (chunk: Buffer) => process.stdout.write(chunk));
    child.stderr.on("data", (chunk: Buffer) => process.stderr.write(chunk));
    child.on("error", (error) => {
      console.error(
        `Could not start "${step.display}": ${error.message}. Did you run npm install?`,
      );
      resolve(1);
    });
    child.on("close", (code) => resolve(code ?? 1));
  });
}

async function main(): Promise<number> {
  for (const [index, step] of STEPS.entries()) {
    console.log(
      `\n==> [${index + 1}/${STEPS.length}] ${step.name}: ${step.display}`,
    );
    const exitCode = await runStep(step);
    if (exitCode !== 0) {
      console.error(
        `\nCheck FAILED at step "${step.name}" (exit code ${exitCode}).`,
      );
      return 1;
    }
  }
  console.log(`\nCheck passed: ${STEPS.map((step) => step.name).join(", ")}.`);
  return 0;
}

process.exitCode = await main();
